
package Frames;

import Class.Cliente;
import Class.Cliente1;
import Class.Configuracion;
import Class.Detalle;
import Class.Evento;
import Class.Producto;
import Class.Producto1;
import Class.Proveedor;
import Class.Proveedor1;
import Class.Venta;
import Class.Venta1;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class Clientefrm extends javax.swing.JFrame {
    Cliente cliente = new Cliente();
    Cliente1 cliente1 = new Cliente1();
    Proveedor proveedor = new Proveedor();
    Proveedor1 proveedor1 = new Proveedor1();
    Producto producto = new Producto();
    Producto1 producto1 = new Producto1();
    Venta venta = new Venta();
    Venta1 venta1 = new Venta1();
    Detalle detalle_venta = new Detalle();
    Configuracion configuracion=new Configuracion();
    Evento event = new Evento();
    DefaultTableModel clase = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    int item;
    double totalpagar = 0.00;
    /**
     * Creates new form Cliente
     */
    public Clientefrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_IDCliente.setVisible(false);
        LimpiarTable();
        ListarCliente();
    }
    
    public void ListarCliente() {
        List<Cliente> listarcliente = cliente1.ListarCliente();
        clase = (DefaultTableModel) table_Cliente.getModel();
        Object[] ob = new Object[6];

        for (int i = 0; i < listarcliente.size(); i++) {
            ob[0] = listarcliente.get(i).getID();
            ob[1] = listarcliente.get(i).getDNI();
            ob[2] = listarcliente.get(i).getNombre();
            ob[3] = listarcliente.get(i).getTelefono();
            ob[4] = listarcliente.get(i).getDireccion();
            ob[5] = listarcliente.get(i).getRazon();
            clase.addRow(ob);
        }
        table_Cliente.setModel(clase);
    }
    public void LimpiarTable() {
        for (int i = 0; i < clase.getRowCount(); i++) {
            clase.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_DNICliente = new javax.swing.JTextField();
        txt_NombreCliente = new javax.swing.JTextField();
        txt_TelefonoCliente = new javax.swing.JTextField();
        txt_DireccionCliente = new javax.swing.JTextField();
        txt_RazonSocialCliente = new javax.swing.JTextField();
        txt_IDCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Cliente = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_EditarCliente = new javax.swing.JLabel();
        btn_GuardarCliente = new javax.swing.JLabel();
        btn_EliminarCliente = new javax.swing.JLabel();
        btn_NuevoCliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes_menu.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, 110));

        jLabel9.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CLIENTES");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 40));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(40, 40));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 40, 40));

        jLabel12.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel12.setText("DNI/RUC:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 20));

        jLabel13.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel13.setText("NOMBRE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, 20));

        jLabel14.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel14.setText("TELEFONO:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, 20));

        jLabel15.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel15.setText("DIRECCIÓN:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 70, 20));

        jLabel16.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel16.setText("RAZON SOCIAL:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, 20));

        txt_DNICliente.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txt_DNICliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_DNICliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DNICliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DNIClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_DNICliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, 20));

        txt_NombreCliente.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txt_NombreCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_NombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_NombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, 20));

        txt_TelefonoCliente.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txt_TelefonoCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_TelefonoCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_TelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelefonoClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_TelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, 20));

        txt_DireccionCliente.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txt_DireccionCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_DireccionCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DireccionCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DireccionClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_DireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 140, 20));

        txt_RazonSocialCliente.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txt_RazonSocialCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_RazonSocialCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_RazonSocialCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RazonSocialClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_RazonSocialCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 140, 20));

        txt_IDCliente.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txt_IDCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_IDCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_IDCliente.setEnabled(false);
        jPanel1.add(txt_IDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 20, 20));

        table_Cliente.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        table_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI/RUC", "Nombre", "Telefono", "Direccion", "Razon Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Cliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 550, 370));

        jLabel6.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACTUALIZAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 80, 20));

        jLabel7.setFont(new java.awt.Font("72", 3, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("LISTADO DE CLIENTES REGISTRADOS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, -1));

        btn_EditarCliente.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        btn_EditarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_EditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/update_icon.png"))); // NOI18N
        btn_EditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EditarCliente.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_EditarCliente.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_EditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditarClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btn_EditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 60, 60));

        btn_GuardarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_GuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar_icon.png"))); // NOI18N
        btn_GuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GuardarCliente.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_GuardarCliente.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_GuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btn_GuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 60, 60));

        btn_EliminarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_EliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_venta.png"))); // NOI18N
        btn_EliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EliminarCliente.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_EliminarCliente.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_EliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EliminarClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btn_EliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 60, 60));

        btn_NuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_NuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btn_NuevoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_NuevoCliente.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_NuevoCliente.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_NuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btn_NuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 60, 60));

        jLabel8.setFont(new java.awt.Font("72", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("REGISTRA UN NUEVO CLIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        jLabel10.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GUARDAR");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 80, 20));

        jLabel11.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NUEVO");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 80, 20));

        jLabel17.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ELIMINAR");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu menu = new Menu ();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void table_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ClienteMouseClicked
        int fila = table_Cliente.rowAtPoint(evt.getPoint());

        txt_IDCliente.setText(table_Cliente.getValueAt(fila, 0).toString());
        txt_DNICliente.setText(table_Cliente.getValueAt(fila, 1).toString());
        txt_NombreCliente.setText(table_Cliente.getValueAt(fila, 2).toString());
        txt_TelefonoCliente.setText(table_Cliente.getValueAt(fila, 3).toString());
        txt_DireccionCliente.setText(table_Cliente.getValueAt(fila, 4).toString());
        txt_RazonSocialCliente.setText(table_Cliente.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_table_ClienteMouseClicked

    private void btn_GuardarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarClienteMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_DNICliente.getText()) && !"".equals(txt_NombreCliente.getText()) && !"".equals(txt_TelefonoCliente.getText()) && !"".equals(txt_DireccionCliente.getText())) {
            cliente.setDNI(Integer.parseInt(txt_DNICliente.getText()));
            cliente.setNombre(txt_NombreCliente.getText());
            cliente.setTelefono(Integer.parseInt(txt_TelefonoCliente.getText()));
            cliente.setDireccion(txt_DireccionCliente.getText());
            cliente.setRazon(txt_RazonSocialCliente.getText());
            cliente1.RegistrarCliente(cliente);
            LimpiarTable();
            LimpiarCliente();
            ListarCliente();
            JOptionPane.showMessageDialog(null, "Cliente Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        }
    }//GEN-LAST:event_btn_GuardarClienteMouseClicked

    private void btn_EditarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditarClienteMouseClicked
        // TODO add your handling code here:
        if ("".equals(txt_IDCliente.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(txt_DNICliente.getText()) && !"".equals(txt_NombreCliente.getText()) && !"".equals(txt_TelefonoCliente.getText()) && !"".equals(txt_DireccionCliente.getText())) {
                cliente.setDNI(Integer.parseInt(txt_DNICliente.getText()));
                cliente.setNombre(txt_NombreCliente.getText());
                cliente.setTelefono(Integer.parseInt(txt_TelefonoCliente.getText()));
                cliente.setDireccion(txt_DireccionCliente.getText());
                cliente.setRazon(txt_RazonSocialCliente.getText());
                cliente.setID(Integer.parseInt(txt_IDCliente.getText()));
                cliente1.ModificarCliente(cliente);
                LimpiarTable();
                LimpiarCliente();
                ListarCliente();
                JOptionPane.showMessageDialog(null, "Cliente Modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Rellene todos los campos");
            }
        }
    }//GEN-LAST:event_btn_EditarClienteMouseClicked

    private void btn_EliminarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarClienteMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_IDCliente.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de Eliminar");

            if (pregunta == 0) {
                int ID = Integer.parseInt(txt_IDCliente.getText());
                cliente1.EliminarCliente(ID);
                LimpiarTable();
                LimpiarCliente();
                ListarCliente();
            } else {
                LimpiarCliente();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }//GEN-LAST:event_btn_EliminarClienteMouseClicked

    private void btn_NuevoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoClienteMouseClicked
        // TODO add your handling code here:
        LimpiarCliente();
    }//GEN-LAST:event_btn_NuevoClienteMouseClicked

    private void txt_DNIClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DNIClienteKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_DNIClienteKeyTyped

    private void txt_NombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreClienteKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_NombreClienteKeyTyped

    private void txt_TelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelefonoClienteKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_TelefonoClienteKeyTyped

    private void txt_DireccionClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DireccionClienteKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_DireccionClienteKeyTyped

    private void txt_RazonSocialClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RazonSocialClienteKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_RazonSocialClienteKeyTyped

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_DNICliente.getText()) && !"".equals(txt_NombreCliente.getText()) && !"".equals(txt_TelefonoCliente.getText()) && !"".equals(txt_DireccionCliente.getText())) {
            cliente.setDNI(Integer.parseInt(txt_DNICliente.getText()));
            cliente.setNombre(txt_NombreCliente.getText());
            cliente.setTelefono(Integer.parseInt(txt_TelefonoCliente.getText()));
            cliente.setDireccion(txt_DireccionCliente.getText());
            cliente.setRazon(txt_RazonSocialCliente.getText());
            cliente1.RegistrarCliente(cliente);
            LimpiarTable();
            LimpiarCliente();
            ListarCliente();
            JOptionPane.showMessageDialog(null, "Cliente Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if ("".equals(txt_IDCliente.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(txt_DNICliente.getText()) && !"".equals(txt_NombreCliente.getText()) && !"".equals(txt_TelefonoCliente.getText()) && !"".equals(txt_DireccionCliente.getText())) {
                cliente.setDNI(Integer.parseInt(txt_DNICliente.getText()));
                cliente.setNombre(txt_NombreCliente.getText());
                cliente.setTelefono(Integer.parseInt(txt_TelefonoCliente.getText()));
                cliente.setDireccion(txt_DireccionCliente.getText());
                cliente.setRazon(txt_RazonSocialCliente.getText());
                cliente.setID(Integer.parseInt(txt_IDCliente.getText()));
                cliente1.ModificarCliente(cliente);
                LimpiarTable();
                LimpiarCliente();
                ListarCliente();
                JOptionPane.showMessageDialog(null, "Cliente Modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Rellene todos los campos");
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_IDCliente.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de Eliminar");

            if (pregunta == 0) {
                int ID = Integer.parseInt(txt_IDCliente.getText());
                cliente1.EliminarCliente(ID);
                LimpiarTable();
                LimpiarCliente();
                ListarCliente();
            } else {
                LimpiarCliente();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        LimpiarCliente();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientefrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_EditarCliente;
    private javax.swing.JLabel btn_EliminarCliente;
    private javax.swing.JLabel btn_GuardarCliente;
    private javax.swing.JLabel btn_NuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_Cliente;
    private javax.swing.JTextField txt_DNICliente;
    private javax.swing.JTextField txt_DireccionCliente;
    private javax.swing.JTextField txt_IDCliente;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_RazonSocialCliente;
    private javax.swing.JTextField txt_TelefonoCliente;
    // End of variables declaration//GEN-END:variables
    private void LimpiarCliente() {
        txt_IDCliente.setText("");
        txt_DNICliente.setText("");
        txt_NombreCliente.setText("");
        txt_TelefonoCliente.setText("");
        txt_DireccionCliente.setText("");
        txt_RazonSocialCliente.setText("");
    }
}
