/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Class.Cliente;
import Class.Cliente1;
import Class.Configuracion;
import Class.Detalle;
import Class.Evento;
import Class.Producto;
import Class.Producto1;
import Class.Proveedor;
import Class.Proveedor1;
import Class.Venta;
import Class.Venta1;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mikeblackhat
 */
public class Configfrm extends javax.swing.JFrame {
    Cliente cliente = new Cliente();
    Cliente1 cliente1 = new Cliente1();
    Proveedor proveedor = new Proveedor();
    Proveedor1 proveedor1 = new Proveedor1();
    Producto producto = new Producto();
    Producto1 producto1 = new Producto1();
    Venta venta = new Venta();
    Venta1 venta1 = new Venta1();
    Detalle detalle_venta = new Detalle();
    Configuracion configuracion=new Configuracion();
    Evento event = new Evento();
    DefaultTableModel clase = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    int item;
    double totalpagar = 0.00;
    /**
     * Creates new form Config
     */
    public Configfrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_IDConfiguracion.setVisible(false);
        ListarConfiguracion();
    }
    
    public void ListarConfiguracion(){
        configuracion=producto1.BuscarDatos();
        txt_IDConfiguracion.setText(""+configuracion.getID());
        txt_RucConfiguracion.setText(""+configuracion.getRuc());
        txt_NombreConfiguracion.setText(""+configuracion.getNombre());
        txt_TelefonoConfiguracion.setText(""+configuracion.getTelefono());
        txt_DireccionConfiguracion.setText(""+configuracion.getDireccion());
        txt_RazonSocialConfiguracion.setText(""+configuracion.getRazon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_NombreConfiguracion = new javax.swing.JTextField();
        txt_RazonSocialConfiguracion = new javax.swing.JTextField();
        txt_TelefonoConfiguracion = new javax.swing.JTextField();
        txt_DireccionConfiguracion = new javax.swing.JTextField();
        txt_IDConfiguracion = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ActualizarBtn = new javax.swing.JLabel();
        txt_RucConfiguracion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config_menu.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, 110));

        jLabel9.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CONFIGURACION");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 330, 40));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(40, 40));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 40, 40));

        jLabel27.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 153, 0));
        jLabel27.setText("RUC :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 30));

        jLabel28.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 153, 0));
        jLabel28.setText("NOMBRE :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 30));

        jLabel29.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 153, 0));
        jLabel29.setText("TELEFONO :");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 130, 30));

        jLabel30.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 153, 0));
        jLabel30.setText("DIRECCIÓN :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 150, 30));

        jLabel31.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 153, 0));
        jLabel31.setText("RAZON SOCIAL :");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, 30));

        txt_NombreConfiguracion.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_NombreConfiguracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreConfiguracionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NombreConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 280, -1));

        txt_RazonSocialConfiguracion.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_RazonSocialConfiguracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RazonSocialConfiguracionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_RazonSocialConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 280, -1));

        txt_TelefonoConfiguracion.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_TelefonoConfiguracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelefonoConfiguracionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_TelefonoConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 280, -1));

        txt_DireccionConfiguracion.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_DireccionConfiguracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DireccionConfiguracionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_DireccionConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 290, -1));

        txt_IDConfiguracion.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jPanel1.add(txt_IDConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 140, -1));

        jLabel32.setFont(new java.awt.Font("72", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 153, 0));
        jLabel32.setText("DATOS DE LA EMPRESA");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logod.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 240, 247));

        jLabel33.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 153, 0));
        jLabel33.setText("Todos los derechos reservados. Contrato de licencia -   TM & © 2022 ChameleonStore.pe. ");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 564, 500, 30));

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));

        ActualizarBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ActualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActualizarBtn.setText("ACTUALIZAR DATOS");
        ActualizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 230, 40));

        txt_RucConfiguracion.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_RucConfiguracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RucConfiguracionKeyTyped(evt);
            }
        });
        jPanel1.add(txt_RucConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu menu = new Menu ();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_RucConfiguracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RucConfiguracionKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_RucConfiguracionKeyTyped

    private void txt_NombreConfiguracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreConfiguracionKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_NombreConfiguracionKeyTyped

    private void txt_RazonSocialConfiguracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RazonSocialConfiguracionKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_RazonSocialConfiguracionKeyTyped

    private void txt_TelefonoConfiguracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelefonoConfiguracionKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_TelefonoConfiguracionKeyTyped

    private void txt_DireccionConfiguracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DireccionConfiguracionKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_DireccionConfiguracionKeyTyped

    private void ActualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarBtnMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_RucConfiguracion.getText()) && !"".equals(txt_NombreConfiguracion.getText()) && !"".equals(txt_TelefonoConfiguracion.getText()) && !"".equals(txt_DireccionConfiguracion.getText()) && !"".equals(txt_RazonSocialConfiguracion)) {
                configuracion.setRuc(Integer.parseInt(txt_RucConfiguracion.getText()));
                configuracion.setNombre(txt_NombreConfiguracion.getText());
                configuracion.setTelefono(Integer.parseInt(txt_TelefonoConfiguracion.getText()));
                configuracion.setDireccion(txt_DireccionConfiguracion.getText());
                configuracion.setRazon(txt_RazonSocialConfiguracion.getText());
                configuracion.setID(Integer.parseInt(txt_IDConfiguracion.getText()));
                producto1.ModificarDatos(configuracion);
                JOptionPane.showMessageDialog(null, "Datos de la empresa Modificado");
                ListarConfiguracion();
            } else {
                JOptionPane.showMessageDialog(null, "Rellene todos los campos");
            }
    }//GEN-LAST:event_ActualizarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualizarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_DireccionConfiguracion;
    private javax.swing.JTextField txt_IDConfiguracion;
    private javax.swing.JTextField txt_NombreConfiguracion;
    private javax.swing.JTextField txt_RazonSocialConfiguracion;
    private javax.swing.JTextField txt_RucConfiguracion;
    private javax.swing.JTextField txt_TelefonoConfiguracion;
    // End of variables declaration//GEN-END:variables
}
