
package Frames;

import java.awt.Color;

/**
 *
 * @author mikeblackhat
 */
public class Menu extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        proveedorlbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ventalbl = new javax.swing.JLabel();
        clientelbl = new javax.swing.JLabel();
        configlbl = new javax.swing.JLabel();
        productolbl = new javax.swing.JLabel();
        reportelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 310, 40));

        proveedorlbl.setFont(new java.awt.Font("72", 1, 12)); // NOI18N
        proveedorlbl.setForeground(new java.awt.Color(51, 153, 0));
        proveedorlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proveedorlbl.setText("PROVEEDORES");
        proveedorlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proveedorlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedorlblMouseClicked(evt);
            }
        });
        jPanel1.add(proveedorlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 100, -1));

        jLabel6.setFont(new java.awt.Font("72", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("ELIJA UNA OPCION...");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 150, 10));

        ventalbl.setFont(new java.awt.Font("72", 1, 12)); // NOI18N
        ventalbl.setForeground(new java.awt.Color(51, 153, 0));
        ventalbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventalbl.setText("GENERAR VENTA");
        ventalbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ventalbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventalblMouseClicked(evt);
            }
        });
        jPanel1.add(ventalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, -1));

        clientelbl.setFont(new java.awt.Font("72", 1, 12)); // NOI18N
        clientelbl.setForeground(new java.awt.Color(51, 153, 0));
        clientelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientelbl.setText("CLIENTES");
        clientelbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientelblMouseClicked(evt);
            }
        });
        jPanel1.add(clientelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 110, -1));

        configlbl.setFont(new java.awt.Font("72", 1, 12)); // NOI18N
        configlbl.setForeground(new java.awt.Color(51, 153, 0));
        configlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configlbl.setText("CONFIGURACION");
        configlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configlblMouseClicked(evt);
            }
        });
        jPanel1.add(configlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 110, 20));

        productolbl.setFont(new java.awt.Font("72", 1, 12)); // NOI18N
        productolbl.setForeground(new java.awt.Color(51, 153, 0));
        productolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productolbl.setText("PRODUCTOS");
        productolbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productolblMouseClicked(evt);
            }
        });
        jPanel1.add(productolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 110, 20));

        reportelbl.setFont(new java.awt.Font("72", 1, 12)); // NOI18N
        reportelbl.setForeground(new java.awt.Color(51, 153, 0));
        reportelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportelbl.setText("REPORTES");
        reportelbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportelblMouseClicked(evt);
            }
        });
        jPanel1.add(reportelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 110, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedor_menu.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 110, 110));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas_menu.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, 110));

        jLabel3.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes_menu.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 110, 110));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config_menu.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 110, 110));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos_menu.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, 110));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes_menu.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 110, 110));

        ExitPanel.setBackground(new java.awt.Color(51, 153, 0));
        ExitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitPanelMouseEntered(evt);
            }
        });

        ExitBtn.setFont(new java.awt.Font("72 Mono", 1, 12)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBtn.setText("X");
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ExitBtnMouseDragged(evt);
            }
        });
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitPanelLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();          // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnMousePressed

    private void ExitBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y - yMouse);         // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnMouseDragged

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
              // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPanelMouseEntered
  // TODO add your handling code here:
    }//GEN-LAST:event_ExitPanelMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
      // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnMouseExited

    private void proveedorlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedorlblMouseClicked
        Proveedorfrm proveedor = new Proveedorfrm ();
        proveedor.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorlblMouseClicked

    private void clientelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientelblMouseClicked
        Clientefrm cliente = new Clientefrm ();
        cliente.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_clientelblMouseClicked

    private void ventalblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventalblMouseClicked
        Ventafrm venta = new Ventafrm();
        venta.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ventalblMouseClicked

    private void productolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productolblMouseClicked
        Productofrm producto = new Productofrm();
        producto.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_productolblMouseClicked

    private void reportelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportelblMouseClicked
        Reportefrm reporte = new Reportefrm();
        reporte.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_reportelblMouseClicked

    private void configlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configlblMouseClicked
        
        Configfrm config = new Configfrm();
        config.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_configlblMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // venta
        Ventafrm venta = new Ventafrm();
        venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // clientes
        Clientefrm cliente = new Clientefrm ();
        cliente.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // proveedores
        Proveedorfrm proveedor = new Proveedorfrm ();
        proveedor.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // productos
        Productofrm producto = new Productofrm();
        producto.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // reporte
        Reportefrm reporte = new Reportefrm();
        reporte.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // configuracion
        Configfrm config = new Configfrm();
        config.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JLabel clientelbl;
    private javax.swing.JLabel configlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productolbl;
    private javax.swing.JLabel proveedorlbl;
    private javax.swing.JLabel reportelbl;
    private javax.swing.JLabel ventalbl;
    // End of variables declaration//GEN-END:variables
}
