/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Class.Cliente;
import Class.Cliente1;
import Class.Configuracion;
import Class.Detalle;
import Class.Evento;
import Class.Producto;
import Class.Producto1;
import Class.Proveedor;
import Class.Proveedor1;
import Class.Venta;
import Class.Venta1;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author mikeblackhat
 */
public class Productofrm extends javax.swing.JFrame {
    Cliente cliente = new Cliente();
    Cliente1 cliente1 = new Cliente1();
    Proveedor proveedor = new Proveedor();
    Proveedor1 proveedor1 = new Proveedor1();
    Producto producto = new Producto();
    Producto1 producto1 = new Producto1();
    Venta venta = new Venta();
    Venta1 venta1 = new Venta1();
    Detalle detalle_venta = new Detalle();
    Configuracion configuracion=new Configuracion();
    Evento event=new Evento();
    DefaultTableModel clase = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    int item;
    double totalpagar = 0.00;
    /**
     * Creates new form Producto
     */
    public Productofrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_IDProducto.setVisible(false);
        AutoCompleteDecorator.decorate(combo_ProveedorProducto);
        producto1.ConsultarProveedor(combo_ProveedorProducto);
        
        LimpiarTable();
        ListarProducto();
    }
    public void ListarProducto() {
        List<Producto> listarproducto = producto1.ListarProducto();
        clase = (DefaultTableModel) table_Producto.getModel();
        Object[] ob = new Object[6];

        for (int i = 0; i < listarproducto.size(); i++) {
            ob[0] = listarproducto.get(i).getID();
            ob[1] = listarproducto.get(i).getCodigo();
            ob[2] = listarproducto.get(i).getNombre();
            ob[3] = listarproducto.get(i).getProveedor();
            ob[4] = listarproducto.get(i).getStock();
            ob[5] = listarproducto.get(i).getPrecio();
            clase.addRow(ob);
        }
        table_Producto.setModel(clase);
    }
    public void LimpiarTable() {
        for (int i = 0; i < clase.getRowCount(); i++) {
            clase.removeRow(i);
            i = i - 1;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_CodigoProducto = new javax.swing.JTextField();
        txt_DescripcionProducto = new javax.swing.JTextField();
        txt_CantidadProducto = new javax.swing.JTextField();
        txt_PrecioProducto = new javax.swing.JTextField();
        combo_ProveedorProducto = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_Producto = new javax.swing.JTable();
        txt_IDProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_GuardarProveedor = new javax.swing.JLabel();
        btn_ActualizarProveedor = new javax.swing.JLabel();
        btn_NuevoProveedor = new javax.swing.JLabel();
        btn_EliminarProveedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos_menu.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, 110));

        jLabel9.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PRODUCTOS");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 40));

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(40, 40));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 40, 40));

        jLabel22.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel22.setText("CODIGO :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jLabel23.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel23.setText("DESCRIPCION :");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 30));

        jLabel24.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel24.setText("CANTIDAD :");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 30));

        jLabel25.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel25.setText("PRECIO :");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 60, 30));

        jLabel26.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel26.setText("PROVEEDOR :");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 30));

        txt_CodigoProducto.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_CodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CodigoProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_CodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, 30));

        txt_DescripcionProducto.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_DescripcionProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DescripcionProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_DescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 190, 30));

        txt_CantidadProducto.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_CantidadProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CantidadProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_CantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, 30));

        txt_PrecioProducto.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        txt_PrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PrecioProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txt_PrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 190, 30));

        combo_ProveedorProducto.setEditable(true);
        combo_ProveedorProducto.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jPanel2.add(combo_ProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 200, 30));

        table_Producto.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        table_Producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Descripción", "Proveedor", "Stock", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ProductoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_Producto);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 124, 490, 320));

        txt_IDProducto.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jPanel2.add(txt_IDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 40, 30));

        jLabel7.setFont(new java.awt.Font("72", 3, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("LISTADO DE PRODUCTOS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 260, -1));

        jLabel6.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACTUALIZAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 80, 20));

        jLabel10.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GUARDAR");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 80, 20));

        jLabel11.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NUEVO");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 80, 20));

        jLabel17.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ELIMINAR");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 80, 20));

        btn_GuardarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_GuardarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar_icon.png"))); // NOI18N
        btn_GuardarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GuardarProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_GuardarProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_GuardarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarProveedorMouseClicked(evt);
            }
        });
        jPanel2.add(btn_GuardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 60, 60));

        btn_ActualizarProveedor.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        btn_ActualizarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ActualizarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/update_icon.png"))); // NOI18N
        btn_ActualizarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ActualizarProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_ActualizarProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_ActualizarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ActualizarProveedorMouseClicked(evt);
            }
        });
        jPanel2.add(btn_ActualizarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 60, 60));

        btn_NuevoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_NuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btn_NuevoProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_NuevoProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_NuevoProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_NuevoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoProveedorMouseClicked(evt);
            }
        });
        jPanel2.add(btn_NuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 60, 60));

        btn_EliminarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_EliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_venta.png"))); // NOI18N
        btn_EliminarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EliminarProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_EliminarProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_EliminarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EliminarProveedorMouseClicked(evt);
            }
        });
        jPanel2.add(btn_EliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu menu = new Menu ();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void table_ProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ProductoMouseClicked
        int fila = table_Producto.rowAtPoint(evt.getPoint());
        txt_IDProducto.setText(table_Producto.getValueAt(fila, 0).toString());
        txt_CodigoProducto.setText(table_Producto.getValueAt(fila, 1).toString());
        txt_DescripcionProducto.setText(table_Producto.getValueAt(fila, 2).toString());
        combo_ProveedorProducto.setSelectedItem(table_Producto.getValueAt(fila, 3).toString());
        txt_CantidadProducto.setText(table_Producto.getValueAt(fila, 4).toString());
        txt_PrecioProducto.setText(table_Producto.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_table_ProductoMouseClicked

    private void btn_GuardarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarProveedorMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_CodigoProducto.getText()) && !"".equals(txt_DescripcionProducto.getText()) && !"".equals(txt_CantidadProducto.getText()) && !"".equals(txt_PrecioProducto.getText()) && !"".equals(combo_ProveedorProducto.getSelectedItem())) {
            producto.setCodigo(txt_CodigoProducto.getText());
            producto.setNombre(txt_DescripcionProducto.getText());
            producto.setProveedor(combo_ProveedorProducto.getSelectedItem().toString());
            producto.setStock(Integer.parseInt(txt_CantidadProducto.getText()));
            producto.setPrecio(Double.parseDouble(txt_PrecioProducto.getText()));
            producto1.RegistrarProducto(producto);
            LimpiarTable();
            ListarProducto();
            LimpiarProducto();
            JOptionPane.showMessageDialog(null, "Producto Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        }
    }//GEN-LAST:event_btn_GuardarProveedorMouseClicked

    private void btn_ActualizarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarProveedorMouseClicked
        // TODO add your handling code here:
        if ("".equals(txt_IDProducto.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {
            if (!"".equals(txt_CodigoProducto.getText()) && !"".equals(txt_DescripcionProducto.getText()) && !"".equals(txt_CantidadProducto.getText()) && !"".equals(txt_PrecioProducto.getText())) {
                producto.setCodigo(txt_CodigoProducto.getText());
                producto.setNombre(txt_DescripcionProducto.getText());
                producto.setProveedor(combo_ProveedorProducto.getSelectedItem().toString());
                producto.setStock(Integer.parseInt(txt_CantidadProducto.getText()));
                producto.setPrecio(Double.parseDouble(txt_PrecioProducto.getText()));
                producto.setID(Integer.parseInt(txt_IDProducto.getText()));
                producto1.ModificarProducto(producto);
                LimpiarTable();
                ListarProducto();
                LimpiarProducto();
                JOptionPane.showMessageDialog(null, "Producto Modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Rellene todos los campos");
            }
        }
    }//GEN-LAST:event_btn_ActualizarProveedorMouseClicked

    private void btn_EliminarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarProveedorMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_IDProducto.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el Producto");
            if (pregunta == 0) {
                int ID = Integer.parseInt(txt_IDProducto.getText());
                producto1.EliminarProducto(ID);
                LimpiarTable();
                ListarProducto();
                LimpiarProducto();
            } else {
                LimpiarProducto();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }//GEN-LAST:event_btn_EliminarProveedorMouseClicked

    private void btn_NuevoProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoProveedorMouseClicked
        // TODO add your handling code here:
        LimpiarProducto();
    }//GEN-LAST:event_btn_NuevoProveedorMouseClicked

    private void txt_CodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CodigoProductoKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_CodigoProductoKeyTyped

    private void txt_DescripcionProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescripcionProductoKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_DescripcionProductoKeyTyped

    private void txt_CantidadProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CantidadProductoKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_CantidadProductoKeyTyped

    private void txt_PrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrecioProductoKeyTyped
        // TODO add your handling code here:
        event.numberDecimalKeyPress(evt, txt_PrecioProducto);
    }//GEN-LAST:event_txt_PrecioProductoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productofrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productofrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_ActualizarProveedor;
    private javax.swing.JLabel btn_EliminarProveedor;
    private javax.swing.JLabel btn_GuardarProveedor;
    private javax.swing.JLabel btn_NuevoProveedor;
    private javax.swing.JComboBox<String> combo_ProveedorProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_Producto;
    private javax.swing.JTextField txt_CantidadProducto;
    private javax.swing.JTextField txt_CodigoProducto;
    private javax.swing.JTextField txt_DescripcionProducto;
    private javax.swing.JTextField txt_IDProducto;
    private javax.swing.JTextField txt_PrecioProducto;
    // End of variables declaration//GEN-END:variables
    private void LimpiarProducto() {
        txt_IDProducto.setText("");
        txt_CodigoProducto.setText("");
        combo_ProveedorProducto.setSelectedItem(null);
        txt_DescripcionProducto.setText("");
        txt_CantidadProducto.setText("");
        txt_PrecioProducto.setText("");

    }
}
