/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Class.Cliente;
import Class.Cliente1;
import Class.Configuracion;
import Class.Detalle;
import Class.Evento;
import Class.Producto;
import Class.Producto1;
import Class.Proveedor;
import Class.Proveedor1;
import Class.Venta;
import Class.Venta1;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


public class Proveedorfrm extends javax.swing.JFrame {
    Cliente cliente = new Cliente();
    Cliente1 cliente1 = new Cliente1();
    Proveedor proveedor = new Proveedor();
    Proveedor1 proveedor1 = new Proveedor1();
    Producto producto = new Producto();
    Producto1 producto1 = new Producto1();
    Venta venta = new Venta();
    Venta1 venta1 = new Venta1();
    Detalle detalle_venta = new Detalle();
    Configuracion configuracion=new Configuracion();
    Evento event= new Evento();
    DefaultTableModel clase = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    int item;
    double totalpagar = 0.00;
    
    /**
     * Creates new form clientes
     */
    public Proveedorfrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_IDProveedor.setVisible(false);
        LimpiarTable();
        ListarProveedor();
    }
    public void ListarProveedor() {
        List<Proveedor> listarproveedor = proveedor1.ListarProveedor();
        clase = (DefaultTableModel) table_Proveedor.getModel();
        Object[] ob = new Object[6];

        for (int i = 0; i < listarproveedor.size(); i++) {
            ob[0] = listarproveedor.get(i).getID();
            ob[1] = listarproveedor.get(i).getRuc();
            ob[2] = listarproveedor.get(i).getNombre();
            ob[3] = listarproveedor.get(i).getTelefono();
            ob[4] = listarproveedor.get(i).getDireccion();
            ob[5] = listarproveedor.get(i).getRazon();
            clase.addRow(ob);
        }
        table_Proveedor.setModel(clase);
    }
    public void LimpiarTable() {
        for (int i = 0; i < clase.getRowCount(); i++) {
            clase.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_RUCProveedor = new javax.swing.JTextField();
        txt_NombreProveedor = new javax.swing.JTextField();
        txt_TelefonoProveedor = new javax.swing.JTextField();
        txt_DireccionProveedor = new javax.swing.JTextField();
        txt_RazonSocialProveedor = new javax.swing.JTextField();
        txt_IDProveedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Proveedor = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_GuardarProveedor = new javax.swing.JLabel();
        btn_ActualizarProveedor = new javax.swing.JLabel();
        btn_NuevoProveedor = new javax.swing.JLabel();
        btn_EliminarProveedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedor_menu.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, 110));

        jLabel9.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PROVEEDORES");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 40));

        jLabel12.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel12.setText("DNI/RUC:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 20));

        jLabel13.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel13.setText("NOMBRE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, 20));

        jLabel14.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel14.setText("TELEFONO:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, 20));

        jLabel15.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel15.setText("DIRECCIÓN:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, 20));

        jLabel16.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel16.setText("RAZON SOCIAL:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, 20));

        txt_RUCProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_RUCProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RUCProveedorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_RUCProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, 20));

        txt_NombreProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_NombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreProveedorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, 20));

        txt_TelefonoProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_TelefonoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelefonoProveedorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_TelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, 20));

        txt_DireccionProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DireccionProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DireccionProveedorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_DireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 140, 20));

        txt_RazonSocialProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_RazonSocialProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RazonSocialProveedorKeyTyped(evt);
            }
        });
        jPanel1.add(txt_RazonSocialProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 130, 20));

        txt_IDProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_IDProveedor.setEnabled(false);
        jPanel1.add(txt_IDProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 20, 20));

        table_Proveedor.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        table_Proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI/RUC", "Nombre", "Telefono", "Dirección", "Razón Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ProveedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Proveedor);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 550, 370));

        jLabel6.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACTUALIZAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 80, 20));

        jLabel7.setFont(new java.awt.Font("72", 3, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("LISTADO DE PROVEEDORES REGISTRADOS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 260, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 40, 40));

        jLabel8.setFont(new java.awt.Font("72", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("REGISTRA UN NUEVO PROVEEDOR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        jLabel10.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GUARDAR");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 80, 20));

        jLabel11.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NUEVO");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 80, 20));

        jLabel17.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ELIMINAR");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 80, 20));

        btn_GuardarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_GuardarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar_icon.png"))); // NOI18N
        btn_GuardarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GuardarProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_GuardarProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_GuardarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarProveedorMouseClicked(evt);
            }
        });
        jPanel1.add(btn_GuardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 60, 60));

        btn_ActualizarProveedor.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        btn_ActualizarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ActualizarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/update_icon.png"))); // NOI18N
        btn_ActualizarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ActualizarProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_ActualizarProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_ActualizarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ActualizarProveedorMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ActualizarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 60, 60));

        btn_NuevoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_NuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btn_NuevoProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_NuevoProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_NuevoProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_NuevoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoProveedorMouseClicked(evt);
            }
        });
        jPanel1.add(btn_NuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 60, 60));

        btn_EliminarProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_EliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_venta.png"))); // NOI18N
        btn_EliminarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EliminarProveedor.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_EliminarProveedor.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_EliminarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EliminarProveedorMouseClicked(evt);
            }
        });
        jPanel1.add(btn_EliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_ProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ProveedorMouseClicked
        int fila = table_Proveedor.rowAtPoint(evt.getPoint());

        txt_IDProveedor.setText(table_Proveedor.getValueAt(fila, 0).toString());
        txt_RUCProveedor.setText(table_Proveedor.getValueAt(fila, 1).toString());
        txt_NombreProveedor.setText(table_Proveedor.getValueAt(fila, 2).toString());
        txt_TelefonoProveedor.setText(table_Proveedor.getValueAt(fila, 3).toString());
        txt_DireccionProveedor.setText(table_Proveedor.getValueAt(fila, 4).toString());
        txt_RazonSocialProveedor.setText(table_Proveedor.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_table_ProveedorMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         Menu menu = new Menu ();
         menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_GuardarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarProveedorMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_RUCProveedor.getText()) && !"".equals(txt_NombreProveedor.getText()) && !"".equals(txt_TelefonoProveedor.getText()) && !"".equals(txt_DireccionProveedor.getText()) && !"".equals(txt_RazonSocialProveedor.getText())) {
            proveedor.setRuc(Integer.parseInt(txt_RUCProveedor.getText()));
            proveedor.setNombre(txt_NombreProveedor.getText());
            proveedor.setTelefono(Integer.parseInt(txt_TelefonoProveedor.getText()));
            proveedor.setDireccion(txt_DireccionProveedor.getText());
            proveedor.setRazon(txt_RazonSocialProveedor.getText());
            proveedor1.RegistrarProveedor(proveedor);
            LimpiarTable();
            ListarProveedor();
            LimpiarProveedor();
            JOptionPane.showMessageDialog(null, "Proveedor Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        }
    }//GEN-LAST:event_btn_GuardarProveedorMouseClicked

    private void btn_ActualizarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarProveedorMouseClicked
        // TODO add your handling code here:
        if ("".equals(txt_IDProveedor.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {
            if (!"".equals(txt_RUCProveedor.getText()) && !"".equals(txt_NombreProveedor.getText()) && !"".equals(txt_TelefonoProveedor.getText()) && !"".equals(txt_DireccionProveedor.getText()) && !"".equals(txt_RazonSocialProveedor.getText())) {
                proveedor.setRuc(Integer.parseInt(txt_RUCProveedor.getText()));
                proveedor.setNombre(txt_NombreProveedor.getText());
                proveedor.setTelefono(Integer.parseInt(txt_TelefonoProveedor.getText()));
                proveedor.setDireccion(txt_DireccionProveedor.getText());
                proveedor.setRazon(txt_RazonSocialProveedor.getText());
                proveedor.setID(Integer.parseInt(txt_IDProveedor.getText()));
                proveedor1.ModificarProveedor(proveedor);
                LimpiarTable();
                ListarProveedor();
                LimpiarProveedor();
                JOptionPane.showMessageDialog(null, "Proveedor Modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Rellene todos los campos");
            }
        }
    }//GEN-LAST:event_btn_ActualizarProveedorMouseClicked

    private void btn_EliminarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarProveedorMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_IDProveedor.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el Proveedor");
            if (pregunta == 0) {
                int ID = Integer.parseInt(txt_IDProveedor.getText());
                proveedor1.EliminarProveedor(ID);
                LimpiarTable();
                ListarProveedor();
                LimpiarProveedor();
            } else {
                LimpiarProveedor();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }//GEN-LAST:event_btn_EliminarProveedorMouseClicked

    private void btn_NuevoProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoProveedorMouseClicked
        // TODO add your handling code here:
        LimpiarProveedor();
    }//GEN-LAST:event_btn_NuevoProveedorMouseClicked

    private void txt_RUCProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RUCProveedorKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_RUCProveedorKeyTyped

    private void txt_NombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreProveedorKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_NombreProveedorKeyTyped

    private void txt_TelefonoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelefonoProveedorKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_TelefonoProveedorKeyTyped

    private void txt_DireccionProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DireccionProveedorKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_DireccionProveedorKeyTyped

    private void txt_RazonSocialProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RazonSocialProveedorKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_RazonSocialProveedorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedorfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedorfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedorfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedorfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedorfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_ActualizarProveedor;
    private javax.swing.JLabel btn_EliminarProveedor;
    private javax.swing.JLabel btn_GuardarProveedor;
    private javax.swing.JLabel btn_NuevoProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_Proveedor;
    private javax.swing.JTextField txt_DireccionProveedor;
    private javax.swing.JTextField txt_IDProveedor;
    private javax.swing.JTextField txt_NombreProveedor;
    private javax.swing.JTextField txt_RUCProveedor;
    private javax.swing.JTextField txt_RazonSocialProveedor;
    private javax.swing.JTextField txt_TelefonoProveedor;
    // End of variables declaration//GEN-END:variables
    private void LimpiarProveedor() {
        txt_IDProveedor.setText("");
        txt_RUCProveedor.setText("");
        txt_NombreProveedor.setText("");
        txt_TelefonoProveedor.setText("");
        txt_DireccionProveedor.setText("");
        txt_RazonSocialProveedor.setText("");
    }
}
