/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Class.Cliente;
import Class.Cliente1;
import Class.Configuracion;
import Class.Detalle;
import Class.Evento;
import Class.Producto;
import Class.Producto1;
import Class.Proveedor;
import Class.Proveedor1;
import Class.Venta;
import Class.Venta1;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


public class Usuariosfrm1 extends javax.swing.JFrame {
    Cliente cliente = new Cliente();
    Cliente1 cliente1 = new Cliente1();
    Proveedor proveedor = new Proveedor();
    Proveedor1 proveedor1 = new Proveedor1();
    Producto producto = new Producto();
    Producto1 producto1 = new Producto1();
    Venta venta = new Venta();
    Venta1 venta1 = new Venta1();
    Detalle detalle_venta = new Detalle();
    Configuracion configuracion=new Configuracion();
    Evento event= new Evento();
    DefaultTableModel clase = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    int item;
    double totalpagar = 0.00;
    
    /**
     * Creates new form clientes
     */
    public Usuariosfrm1() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_IDUsuario.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_correoUser = new javax.swing.JTextField();
        txt_NombreUser = new javax.swing.JTextField();
        txt_IDUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_GuardarUsuario = new javax.swing.JLabel();
        btn_ActualizarUsuario = new javax.swing.JLabel();
        btn_NuevoUsuario = new javax.swing.JLabel();
        btn_EliminarUsuario = new javax.swing.JLabel();
        cbxRolUser = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(490, 390));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo-usuario.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 110, 110));

        jLabel9.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("USUARIOS");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 280, 40));

        jLabel12.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel12.setText("E-MAIL :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 20));

        jLabel13.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel13.setText("NOMBRE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, 20));

        jLabel14.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel14.setText("ROL :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, 20));

        txt_correoUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_correoUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_correoUserKeyTyped(evt);
            }
        });
        jPanel1.add(txt_correoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 20));

        txt_NombreUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_NombreUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreUserKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 20));

        txt_IDUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_IDUsuario.setEnabled(false);
        jPanel1.add(txt_IDUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 20, 20));

        jLabel6.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACTUALIZAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, 20));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 40, 40));

        jLabel10.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GUARDAR");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, 20));

        jLabel11.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NUEVO");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 80, 20));

        jLabel17.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ELIMINAR");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 80, 20));

        btn_GuardarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_GuardarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar_icon.png"))); // NOI18N
        btn_GuardarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_GuardarUsuario.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_GuardarUsuario.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_GuardarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GuardarUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(btn_GuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 60, 60));

        btn_ActualizarUsuario.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        btn_ActualizarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ActualizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/update_icon.png"))); // NOI18N
        btn_ActualizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ActualizarUsuario.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_ActualizarUsuario.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_ActualizarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ActualizarUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ActualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 60, 60));

        btn_NuevoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_NuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btn_NuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_NuevoUsuario.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_NuevoUsuario.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_NuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(btn_NuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 60, 60));

        btn_EliminarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_EliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_venta.png"))); // NOI18N
        btn_EliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_EliminarUsuario.setMaximumSize(new java.awt.Dimension(40, 16));
        btn_EliminarUsuario.setMinimumSize(new java.awt.Dimension(40, 16));
        btn_EliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EliminarUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(btn_EliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 60, 60));

        cbxRolUser.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        cbxRolUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        cbxRolUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRolUserActionPerformed(evt);
            }
        });
        jPanel1.add(cbxRolUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 140, -1));

        jLabel5.setFont(new java.awt.Font("72", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("Registra un nuevo usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         Menu menu = new Menu ();
         menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_GuardarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GuardarUsuarioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_GuardarUsuarioMouseClicked

    private void btn_ActualizarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ActualizarUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ActualizarUsuarioMouseClicked

    private void btn_EliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EliminarUsuarioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_EliminarUsuarioMouseClicked

    private void btn_NuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoUsuarioMouseClicked
        // TODO add your handling code here:
        LimpiarProveedor();
    }//GEN-LAST:event_btn_NuevoUsuarioMouseClicked

    private void txt_correoUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoUserKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_correoUserKeyTyped

    private void txt_NombreUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreUserKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_NombreUserKeyTyped

    private void cbxRolUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRolUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRolUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuariosfrm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuariosfrm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuariosfrm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuariosfrm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuariosfrm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_ActualizarUsuario;
    private javax.swing.JLabel btn_EliminarUsuario;
    private javax.swing.JLabel btn_GuardarUsuario;
    private javax.swing.JLabel btn_NuevoUsuario;
    private javax.swing.JComboBox<String> cbxRolUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_IDUsuario;
    private javax.swing.JTextField txt_NombreUser;
    private javax.swing.JTextField txt_correoUser;
    // End of variables declaration//GEN-END:variables
    private void LimpiarProveedor() {
        txt_IDUsuario.setText("");
        txt_correoUser.setText("");
        txt_NombreUser.setText("");
    }
}
