/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Class.Cliente;
import Class.Cliente1;
import Class.Configuracion;
import Class.Detalle;
import Class.Evento;
import Class.Producto;
import Class.Producto1;
import Class.Proveedor;
import Class.Proveedor1;
import Class.Venta;
import Class.Venta1;
import Reporte.Grafico;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfName;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import sun.awt.AppContext;

/**
 *
 * @author mikeblackhat
 */
public class Ventafrm extends javax.swing.JFrame {

    /**
     * Creates new form Ventafrm
     */
    Date fechaVenta = new Date();
    String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(fechaVenta);
    Cliente cliente = new Cliente();
    Cliente1 cliente1 = new Cliente1();
    Proveedor proveedor = new Proveedor();
    Proveedor1 proveedor1 = new Proveedor1();
    Producto producto = new Producto();
    Producto1 producto1 = new Producto1();
    Venta venta = new Venta();
    Venta1 venta1 = new Venta1();
    Detalle detalle_venta = new Detalle();
    Configuracion configuracion=new Configuracion();
    Configfrm configfrm=new Configfrm();
    Evento event= new Evento();
    DefaultTableModel clase = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    int item;
    double totalpagar = 0.00;

    public Ventafrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        //txt_IDCliente.setVisible(false);
        txt_IDVenta1.setVisible(false);
        //txt_IDProveedor.setVisible(false);
        //txt_IDProducto.setVisible(false);
        txt_TelefonoClienteVenta.setVisible(false);
        txt_DireccionClienteVenta.setVisible(false);
        txt_RazonClienteVenta.setVisible(false);
        //AutoCompleteDecorator.decorate(combo_ProveedorProducto);
        //producto1.ConsultarProveedor(combo_ProveedorProducto);
        //txt_IDConfiguracion.setVisible(false);
        //ListarConfiguracion();
    }

    

   


    public void LimpiarTable() {
        for (int i = 0; i < clase.getRowCount(); i++) {
            clase.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_CodigoVenta = new javax.swing.JTextField();
        txt_DescripcionVenta = new javax.swing.JTextField();
        txt_CantidadVenta = new javax.swing.JTextField();
        txt_PrecioVenta = new javax.swing.JTextField();
        txt_StockDisponible = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Venta1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_RucVenta = new javax.swing.JTextField();
        txt_NombreClienteVenta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        txt_TelefonoClienteVenta = new javax.swing.JTextField();
        txt_DireccionClienteVenta = new javax.swing.JTextField();
        txt_RazonClienteVenta = new javax.swing.JTextField();
        txt_IDVenta1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_GenerarVenta = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_vendedor = new javax.swing.JLabel();
        Btn_Graficar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Midate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas_menu.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, 110));

        jLabel9.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VENTAS");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 40));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(40, 40));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 40, 40));

        jLabel3.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("CODIGO :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 20));

        jLabel4.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("DESCRIPCION DEL PRODUCTO :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 250, 20));

        jLabel5.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("CANTIDAD :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 80, 20));

        jLabel6.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("PRECIO :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 80, 20));

        jLabel7.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("STOCK :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 80, 20));

        txt_CodigoVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_CodigoVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_CodigoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CodigoVentaActionPerformed(evt);
            }
        });
        txt_CodigoVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CodigoVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CodigoVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_CodigoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 20));

        txt_DescripcionVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_DescripcionVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DescripcionVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DescripcionVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_DescripcionVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 260, 20));

        txt_CantidadVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_CantidadVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_CantidadVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_CantidadVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CantidadVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_CantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, 20));

        txt_PrecioVenta.setEditable(false);
        txt_PrecioVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_PrecioVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_PrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PrecioVentaActionPerformed(evt);
            }
        });
        txt_PrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PrecioVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_PrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 80, 20));

        txt_StockDisponible.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_StockDisponible.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_StockDisponible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_StockDisponibleKeyTyped(evt);
            }
        });
        jPanel1.add(txt_StockDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 80, 20));

        table_Venta1.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        table_Venta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Cantidad", "Precio Unitario", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(table_Venta1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 807, 211));

        jLabel8.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel8.setText("DNI/RUC :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel10.setText("NOMBRE :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        txt_RucVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_RucVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_RucVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RucVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_RucVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 120, -1));

        txt_NombreClienteVenta.setEditable(false);
        txt_NombreClienteVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_NombreClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreClienteVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txt_NombreClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 160, -1));

        jLabel11.setFont(new java.awt.Font("72", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        jLabel11.setText("MONTO A PAGAR :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 180, 70));

        lbl_Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Total.setText("----");
        lbl_Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbl_TotalKeyTyped(evt);
            }
        });
        jPanel1.add(lbl_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 70, -1));

        txt_TelefonoClienteVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_TelefonoClienteVenta.setEnabled(false);
        jPanel1.add(txt_TelefonoClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 20, -1));

        txt_DireccionClienteVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_DireccionClienteVenta.setEnabled(false);
        jPanel1.add(txt_DireccionClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 20, -1));

        txt_RazonClienteVenta.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jPanel1.add(txt_RazonClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 20, -1));

        txt_IDVenta1.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        txt_IDVenta1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txt_IDVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 20, 20));

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));

        jLabel13.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ELIMINAR");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 70, 20));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_venta.png"))); // NOI18N
        jLabel14.setText("eliminar");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 50, 50));

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));

        btn_GenerarVenta.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        btn_GenerarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btn_GenerarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_GenerarVenta.setText("GENERAR");
        btn_GenerarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_GenerarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_GenerarVentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_GenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_GenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 70, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/generar_icon.png"))); // NOI18N
        jLabel15.setText("Generar boleta");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 50, 50));

        lbl_vendedor.setText("danilore");
        jPanel1.add(lbl_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        Btn_Graficar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn_Graficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grafico-circular.png"))); // NOI18N
        Btn_Graficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_GraficarMouseClicked(evt);
            }
        });
        jPanel1.add(Btn_Graficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 40, 40));

        jLabel12.setFont(new java.awt.Font("72", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("SELECCIONE UNA FECHA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 160, 20));
        jPanel1.add(Midate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Menu menu = new Menu ();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_CodigoVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CodigoVentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txt_CodigoVenta.getText())) {
                String codigo = txt_CodigoVenta.getText();
                producto = producto1.BuscarProductos(codigo);
                if (producto.getNombre() != null) {
                    txt_DescripcionVenta.setText("" + producto.getNombre());
                    txt_PrecioVenta.setText("" + producto.getPrecio());
                    txt_StockDisponible.setText("" + producto.getStock());
                    txt_CantidadVenta.requestFocus();
                } else {
                    LimpiarVenta();
                    txt_CodigoVenta.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el código del producto");
                txt_CodigoVenta.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_CodigoVentaKeyPressed

    private void txt_CantidadVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CantidadVentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txt_CantidadVenta.getText())) {
                String codigo = txt_CodigoVenta.getText();
                String descripcion = txt_DescripcionVenta.getText();
                int cantidad = Integer.parseInt(txt_CantidadVenta.getText());
                double precio = Double.parseDouble(txt_PrecioVenta.getText());
                double total = cantidad * precio;
                int stock = Integer.parseInt(txt_StockDisponible.getText());
                if (stock >= cantidad) {
                    item = item + 1;
                    tmp = (DefaultTableModel) table_Venta1.getModel();
                    for (int i = 0; i < table_Venta1.getRowCount(); i++) {
                        if (table_Venta1.getValueAt(i, 1).equals(txt_DescripcionVenta.getText())) {
                            JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                            return;
                        }
                    }
                    ArrayList lista = new ArrayList();
                    lista.add(item);
                    lista.add(codigo);
                    lista.add(descripcion);
                    lista.add(cantidad);
                    lista.add(precio);
                    lista.add(total);
                    Object[] obj = new Object[5];
                    obj[0] = lista.get(1);
                    obj[1] = lista.get(2);
                    obj[2] = lista.get(3);
                    obj[3] = lista.get(4);
                    obj[4] = lista.get(5);
                    tmp.addRow(obj);
                    table_Venta1.setModel(tmp);
                    TotalPagar();
                    LimpiarVenta();
                    txt_CodigoVenta.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Stock no disponible");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese cantidad");
            }
        }
    }//GEN-LAST:event_txt_CantidadVentaKeyPressed

    private void txt_PrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PrecioVentaActionPerformed

    private void txt_RucVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RucVentaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txt_RucVenta.getText())) {
                int DNI = Integer.parseInt(txt_RucVenta.getText());
                cliente = cliente1.BuscarCliente(DNI);
                if (cliente.getNombre() != null) {
                    txt_NombreClienteVenta.setText("" + cliente.getNombre());
                    txt_TelefonoClienteVenta.setText("" + cliente.getTelefono());
                    txt_DireccionClienteVenta.setText("" + cliente.getDireccion());
                    txt_RazonClienteVenta.setText("" + cliente.getRazon());
                } else {
                    txt_RucVenta.setText("");
                    JOptionPane.showMessageDialog(null, "El Cliente no existe");
                }
            }
        }
    }//GEN-LAST:event_txt_RucVentaKeyPressed

    private void txt_CodigoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CodigoVentaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_CodigoVentaActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        clase = (DefaultTableModel) table_Venta1.getModel();
        clase.removeRow(table_Venta1.getSelectedRow());
        TotalPagar();
        txt_CodigoVenta.requestFocus();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        clase = (DefaultTableModel) table_Venta1.getModel();
        clase.removeRow(table_Venta1.getSelectedRow());
        TotalPagar();
        txt_CodigoVenta.requestFocus();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_RucVenta.getText())) {
            if (!"".equals(txt_NombreClienteVenta.getText())) {
                RegistrarVenta();
                RegistrarDetalle();
                ActualizarStock();
                PDF();
                LimpiarTableVenta();
                LimpiarClienteVenta();

            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un DNI/RUC valido");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el DNI/RUC");
            txt_RucVenta.requestFocus();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btn_GenerarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GenerarVentaMouseClicked
        // TODO add your handling code here:
        if (!"".equals(txt_RucVenta.getText())) {
            if (!"".equals(txt_NombreClienteVenta.getText())) {
                RegistrarVenta();
                RegistrarDetalle();
                ActualizarStock();
                PDF();
                LimpiarTableVenta();
                LimpiarClienteVenta();

            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un DNI/RUC valido");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el DNI/RUC");
            txt_RucVenta.requestFocus();
        }
    }//GEN-LAST:event_btn_GenerarVentaMouseClicked

    private void txt_CodigoVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CodigoVentaKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_CodigoVentaKeyTyped

    private void txt_DescripcionVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescripcionVentaKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_DescripcionVentaKeyTyped

    private void txt_CantidadVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CantidadVentaKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_CantidadVentaKeyTyped

    private void txt_PrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrecioVentaKeyTyped
        // TODO add your handling code here:
        event.numberDecimalKeyPress(evt, txt_PrecioVenta);
    }//GEN-LAST:event_txt_PrecioVentaKeyTyped

    private void txt_StockDisponibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_StockDisponibleKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_StockDisponibleKeyTyped

    private void txt_RucVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RucVentaKeyTyped
        // TODO add your handling code here:
        event.numberKeyPress(evt);
    }//GEN-LAST:event_txt_RucVentaKeyTyped

    private void txt_NombreClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreClienteVentaKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txt_NombreClienteVentaKeyTyped

    private void lbl_TotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_TotalKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lbl_TotalKeyTyped

    private void Btn_GraficarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_GraficarMouseClicked
        String fechaReporte = new SimpleDateFormat("dd/MM/yyyy").format(Midate.getDate());
        Grafico.Graficar(fechaReporte);        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_GraficarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventafrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_Graficar;
    private com.toedter.calendar.JDateChooser Midate;
    private javax.swing.JLabel btn_GenerarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JLabel lbl_vendedor;
    private javax.swing.JTable table_Venta1;
    private javax.swing.JTextField txt_CantidadVenta;
    private javax.swing.JTextField txt_CodigoVenta;
    private javax.swing.JTextField txt_DescripcionVenta;
    private javax.swing.JTextField txt_DireccionClienteVenta;
    private javax.swing.JTextField txt_IDVenta1;
    private javax.swing.JTextField txt_NombreClienteVenta;
    private javax.swing.JTextField txt_PrecioVenta;
    private javax.swing.JTextField txt_RazonClienteVenta;
    private javax.swing.JTextField txt_RucVenta;
    private javax.swing.JTextField txt_StockDisponible;
    private javax.swing.JTextField txt_TelefonoClienteVenta;
    // End of variables declaration//GEN-END:variables
  

    

    

    private void TotalPagar() {
        totalpagar = 0.00;
        int nfila = table_Venta1.getRowCount();
        for (int i = 0; i < nfila; i++) {
            double calcular = Double.parseDouble(String.valueOf(table_Venta1.getModel().getValueAt(i, 4)));
            totalpagar = totalpagar + calcular;
        }
        lbl_Total.setText(String.format("%.2f", totalpagar));
    }

    private void LimpiarVenta() {
        txt_CodigoVenta.setText("");
        txt_DescripcionVenta.setText("");
        txt_CantidadVenta.setText("");
        txt_PrecioVenta.setText("");
        txt_StockDisponible.setText("");
        txt_IDVenta1.setText("");
    }

    private void RegistrarVenta() {
        String Cliente = txt_NombreClienteVenta.getText();
        String vendedor = lbl_vendedor.getText();
        Double monto = totalpagar;
        venta.setCliente(Cliente);
        venta.setVendedor(vendedor);
        venta.setTotal(monto);
        venta.setFecha(fechaActual);
        venta1.RegistrarVenta(venta);
    }

    private void RegistrarDetalle() {
        int ID = venta1.IDVenta();
        for (int i = 0; i < table_Venta1.getRowCount(); i++) {
            String codigo_producto = table_Venta1.getValueAt(i, 0).toString();
            int cantidad = Integer.parseInt(table_Venta1.getValueAt(i, 2).toString());
            double precio = Double.parseDouble(table_Venta1.getValueAt(i, 3).toString());

            detalle_venta.setCodigo_producto(codigo_producto);
            detalle_venta.setCantidad(cantidad);
            detalle_venta.setPrecio(precio);
            detalle_venta.setID_Venta(ID);
            venta1.RegistrarDetalle(detalle_venta);

        }
    }

    private void ActualizarStock() {
        for (int i = 0; i < table_Venta1.getRowCount(); i++) {
            String codigo = table_Venta1.getValueAt(i, 0).toString();
            int cantidad = Integer.parseInt(table_Venta1.getValueAt(i, 2).toString());
            producto = producto1.BuscarProductos(codigo);
            int StockActual = producto.getStock() - cantidad;
            venta1.ActualizarStock(StockActual, codigo);
        }
    }

    private void LimpiarTableVenta() {
        tmp = (DefaultTableModel) table_Venta1.getModel();
        int fila = table_Venta1.getRowCount();
        for (int i = 0; i < fila; i++) {
            tmp.removeRow(0);
        }
    }

    private void LimpiarClienteVenta() {
        txt_RucVenta.setText("");
        txt_NombreClienteVenta.setText("");
        txt_TelefonoClienteVenta.setText("");
        txt_DireccionClienteVenta.setText("");
        txt_RazonClienteVenta.setText("");
    }
    
    private void PDF(){
        try{
            int ID=venta1.IDVenta();
            FileOutputStream archivo;
            File file = new File("src/PDF/venta"+ID+".pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/Imagenes/1-chameleon.png");
            
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN,12, Font.BOLD, BaseColor.GREEN);
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("factura: "+ID+"\n"+"Fecha: "+new SimpleDateFormat("dd-mm-yyyy").format(date)+"\n\n");
            
            PdfPTable encabezado = new PdfPTable(4);
            encabezado.setWidthPercentage(100);
            encabezado.getDefaultCell().setBorder(0);
            float[] columnaencabezado = new float[]{20f,30f,70f,40f};
            encabezado.setWidths(columnaencabezado);
            encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
            encabezado.addCell(img);
      
            String ruc = "78954654";
            String nombre="ChameleonStore";
            String telefono="936081881";
            String direccion="Chimbote";
            String razon="ChameleonStore";
                                   
            encabezado.addCell("");
            encabezado.addCell("RUC: "+ruc+"\nNombre: "+nombre+"\nTelefono: "+telefono+"\nDireccion: "+direccion+"\nRazon: "+razon);
            encabezado.addCell(fecha);
            doc.add(encabezado);
            
            Paragraph clientes=new Paragraph();
            clientes.add(Chunk.NEWLINE);
            clientes.add("Datos de los clientes"+"\n\n");
            doc.add(clientes);
            
            PdfPTable tablacliente = new  PdfPTable(4);
            tablacliente.setWidthPercentage(100);
            tablacliente.getDefaultCell().setBorder(0);
            float[] columnacliente = new float[]{20f,50f,30f,40f};
            tablacliente.setWidths(columnacliente);
            tablacliente.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell clientes1=new PdfPCell(new Phrase("DNI/Ruc", negrita));
            PdfPCell clientes2=new PdfPCell(new Phrase("Nombre", negrita));
            PdfPCell clientes3=new PdfPCell(new Phrase("Telefono",negrita));
            PdfPCell clientes4=new PdfPCell(new Phrase("Direccion", negrita));
            clientes1.setBorder(0);
            clientes2.setBorder(0);
            clientes3.setBorder(0);
            clientes4.setBorder(0);
            tablacliente.addCell(clientes1);
            tablacliente.addCell(clientes2);
            tablacliente.addCell(clientes3);
            tablacliente.addCell(clientes4);
            tablacliente.addCell(txt_RucVenta.getText());
            tablacliente.addCell(txt_NombreClienteVenta.getText());
            tablacliente.addCell(txt_TelefonoClienteVenta.getText());
            tablacliente.addCell(txt_DireccionClienteVenta.getText());
            
            doc.add(tablacliente);
            
            //productos
            
            PdfPTable tablaproductos = new  PdfPTable(4);
            tablaproductos.setWidthPercentage(100);
            tablaproductos.getDefaultCell().setBorder(0);
            float[] columnaproductos = new float[]{10f,50f,15f,20f};
            tablaproductos.setWidths(columnaproductos);
            tablaproductos.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell productos1=new PdfPCell(new Phrase("Cantidad", negrita));
            PdfPCell productos2=new PdfPCell(new Phrase("Descripcion", negrita));
            PdfPCell productos3=new PdfPCell(new Phrase("Precio U.", negrita));
            PdfPCell productos4=new PdfPCell(new Phrase("Precio T.", negrita));
            productos1.setBorder(0);
            productos2.setBorder(0);
            productos3.setBorder(0);
            productos4.setBorder(0);
            productos1.setBackgroundColor(BaseColor.DARK_GRAY);
            productos2.setBackgroundColor(BaseColor.DARK_GRAY);
            productos3.setBackgroundColor(BaseColor.DARK_GRAY);
            productos4.setBackgroundColor(BaseColor.DARK_GRAY);
            tablaproductos.addCell(productos1);
            tablaproductos.addCell(productos2);
            tablaproductos.addCell(productos3);
            tablaproductos.addCell(productos4);
            for(int i=0;i<table_Venta1.getRowCount();i++){
                String productos = table_Venta1.getValueAt(i, 1).toString();
                String cantidad = table_Venta1.getValueAt(i, 2).toString();
                String precio = table_Venta1.getValueAt(i, 3).toString();
                String total = table_Venta1.getValueAt(i, 4).toString();
                tablaproductos.addCell(cantidad);
                tablaproductos.addCell(productos);
                tablaproductos.addCell(precio);
                tablaproductos.addCell(total);
            }
            doc.add(tablaproductos);
            
            
            Paragraph info = new Paragraph();
            info.add(Chunk.NEWLINE);
            info.add("Total a Pagar: "+totalpagar);
            info.setAlignment(Element.ALIGN_RIGHT);
            doc.add(info);
            
            Paragraph firma = new Paragraph();
            firma.add(Chunk.NEWLINE);
            firma.add("Cancelacion y Firma\n\n");
            firma.add("--------------------");
            firma.setAlignment(Element.ALIGN_CENTER);
            doc.add(firma);
            
            Paragraph mensaje = new Paragraph();
            mensaje.add(Chunk.NEWLINE);
            mensaje.add("Gracias por su preferencia");;
            mensaje.setAlignment(Element.ALIGN_CENTER);
            doc.add(mensaje);
            
            doc.close();
            archivo.close();
            Desktop.getDesktop().open(file);
        }catch(DocumentException | IOException e){
            System.out.println(e.toString());
            
        }
    }

    private void setCliente(String Cliente) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
